quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=guna123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/softvent_finflow
quarkus.datasource.jdbc.timezone=UTC

#maps java objects or entities to table, generation = none -> tells it not to update the schema
quarkus.hibernate-orm.database.generation=none

# E-MAIL CONFIG
quarkus.mailer.from=gunanka2594@gmail.com

quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED

quarkus.mailer.username=gunanka2594@gmail.com
quarkus.mailer.password=jaylfjzietqdkxjk

quarkus.mailer.auth=true
quarkus.mailer.ssl=false
quarkus.mailer.mock=false

quarkus.log.category."io.quarkus.mailer".level=DEBUG

# CORS CONFIG
# Enable the Quarkus CORS filter
quarkus.http.cors.enabled=true

# Specify the allowed origins (your Angular app's URL)
quarkus.http.cors.origins=http://localhost:4200

# Specify the allowed HTTP methods, including OPTIONS for preflight requests and POST for the login
quarkus.http.cors.methods=POST, OPTIONS, GET, PUT, DELETE

# Specify allowed headers (Content-Type, Authorization, etc., as needed by your request)
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with

# Configure how long the browser can cache the preflight request results (optional)
quarkus.http.cors.access-control-max-age=24H

# Allow credentials (e.g., cookies, auth headers) if your frontend sends them
quarkus.http.cors.access-control-allow-credentials=true

mp.jwt.verify.issuer=finflow
smallrye.jwt.sign.key.location=privateKey.pem
