quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=guna123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/softvent_finflow

#maps java objects or entities to table, generation = none -> tells it not to update the schema
quarkus.hibernate-orm.database.generation=none

quarkus.mailer.from=gunanka2594@gmail.com

quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED

quarkus.mailer.username=gunanka2594@gmail.com
quarkus.mailer.password=jaylfjzietqdkxjk

quarkus.mailer.auth=true
quarkus.mailer.ssl=false
quarkus.mailer.mock=false

quarkus.log.category."io.quarkus.mailer".level=DEBUG

