quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=guna123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/softvent_finflow

#maps java objects or entities to table, generation = none -> tells it not to update the schema
quarkus.hibernate-orm.database.generation=none
